class ArtistsBio {
  String name;
  String birthPlace;
  String birthDay;
  String img;
  String description;
  ArtistsBio({
    required this.name,
    required this.birthPlace,
    required this.birthDay,
    required this.img,
    required this.description,
  });
  static List<ArtistsBio> artistsBio() {
    return [
      ArtistsBio(
        name: "Jay-Z",
        birthPlace: 'New York City, U.S.',
        birthDay: "December 4, 1969",
        img: "images/jayz.jpg",
        description:
            """Shawn Corey Carter (born December 4, 1969), known professionally as Jay-Z,[a] is an American rapper, record producer, entrepreneur, and founder of Manhattan-based conglomerate talent and entertainment agency Roc Nation. He is regarded as one of the greatest rappers of all time.[8] He was the CEO of Def Jam Recordings and he has been central to the creative and commercial success of artists including Kanye West, Rihanna, and J. Cole.[9][10]

Born and raised in New York City, Jay-Z first began his musical career in the late 1980s; he co-founded the record label Roc-A-Fella Records in 1995 and released his debut studio album Reasonable Doubt in 1996. The album was released to widespread critical success, and solidified his standing in the music industry. He went on to release twelve additional albums, including the acclaimed albums The Blueprint (2001), The Black Album (2003), American Gangster (2007), and 4:44 (2017).[11][12] He also released the full-length collaborative albums Watch the Throne (2011) with Kanye West and Everything Is Love (2018) with his wife Beyoncé, respectively.[13]

Through his business ventures Jay-Z has become the first hip-hop billionaire.[14][15] In 1999, he founded the clothing retailer Rocawear,[16] and in 2003, he founded the luxury sports bar chain 40/40 Club. Both businesses have grown to become multi-million-dollar corporations, and allowed him to start up Roc Nation in 2008. In 2015, he acquired the tech company Aspiro and took charge of their media streaming service Tidal.[17][18] In 2020, he launched "Monogram", a line of cannabis products.[19]

One of the world's best-selling music artists, with over 140 million records sold, Jay-Z has won 24 Grammy Awards, the joint-most Grammy awards of any rapper along with Kanye West. Jay-Z also holds the record for the most number-one albums by a solo artist on the Billboard 200 (14).[20][21] Additionally, he is a recipient of the NAACP's President's Award, a Primetime Emmy Award, and a Sports Emmy Award; and has also received a nomination for a Tony Award. Ranked by Billboard and Rolling Stone as one of the 100 Greatest Artists of All Time,[22][23] Jay-Z was the first rapper honored in the Songwriters Hall of Fame,[24] and the first solo living rapper inducted in the Rock and Roll Hall of Fame.[25] In 2013, Time named him one of the 100 most influential people in the world.[26]""",
      ),
      ArtistsBio(
          name: "Eminem",
          birthPlace: 'St. Joseph, Missouri, U.S.',
          birthDay: "October 17, 1972",
          img: "images/em.jpg",
          description:
              """Marshall Bruce Mathers III (born October 17, 1972), known professionally as Eminem (/ˌɛmɪˈnɛm/; often stylized as EMINƎM), is an American rapper. He is credited with popularizing hip hop in middle America and is critically acclaimed as one of the greatest rappers of all time.[2] Eminem's global success and acclaimed works are widely regarded as having broken racial barriers for the acceptance of white rappers in popular music. While much of his transgressive work during the late 1990s and early 2000s made him widely controversial, he came to be a representation of popular angst of the American underclass and has been cited as an influence for many artists of various genres.

After the release of his debut album Infinite (1996) and the extended play Slim Shady EP (1997), Eminem signed with Dr. Dre's Aftermath Entertainment and subsequently achieved mainstream popularity in 1999 with The Slim Shady LP. His next two releases, The Marshall Mathers LP (2000) and The Eminem Show (2002), were worldwide successes and were both nominated for the Grammy Award for Album of the Year. After the release of his next album, Encore (2004), Eminem went on hiatus in 2005, largely due to a prescription drug addiction.[3] He returned to the music industry four years later with the release of Relapse (2009) and Recovery was released the following year. Recovery was the best-selling album worldwide of 2010, making it Eminem's second album, after The Eminem Show in 2002, to be the best-selling album of the year worldwide. In the following years, he released the US number one albums The Marshall Mathers LP 2 (2013), Revival (2017), Kamikaze (2018) and Music to Be Murdered By (2020).

Eminem made his debut in the film industry with the musical drama film 8 Mile (2002), playing a fictionalized version of himself, and his track "Lose Yourself" from its soundtrack won the Academy Award for Best Original Song, making him the first hip hop artist ever to win the award.[4] Eminem has made cameo appearances in the films The Wash (2001), Funny People (2009) and The Interview (2014) and the television series Entourage (2010). He has also developed other ventures, including Shady Records, a joint venture with manager Paul Rosenberg, which helped launch the careers of artists such as 50 Cent, D12 and Obie Trice, among others. He has also established his own channel, Shade 45, on Sirius XM Radio.

In addition to his solo career, Eminem was a member of the hip hop group D12. He is also known for collaborations with fellow Detroit-based rapper Royce da 5'9"; the two are collectively known as Bad Meets Evil.

Eminem is among the best-selling music artists of all time, with estimated worldwide sales of over 220 million records. He was the best-selling music artist in the United States of the 2000s and the best-selling male music artist in the United States of the 2010s, third overall. Billboard named him the "Artist of the Decade (2000–2009)". He has had ten number-one albums on the Billboard 200—which all consecutively debuted at number one on the chart, making him the first artist to achieve this[5]—and five number-one singles on the Billboard Hot 100.[6] The Marshall Mathers LP, The Eminem Show, Curtain Call: The Hits (2005), "Lose Yourself", "Love the Way You Lie" and "Not Afraid" have all been certified Diamond or higher by the Recording Industry Association of America (RIAA).[7] Rolling Stone has included him in its lists of the 100 Greatest Artists of All Time and the 100 Greatest Songwriters of All Time. He has won numerous awards, including 15 Grammy Awards, eight American Music Awards, 17 Billboard Music Awards, an Academy Award, a Primetime Emmy Award and an MTV Europe Music Global Icon Award. In November 2022, Eminem was inducted into the Rock and Roll Hall of Fame.[8]"""),
      ArtistsBio(
          name: "Notorious\n B.I.G.",
          birthPlace: 'New York City, U.S.',
          birthDay: "May 21, 1972",
          img: "images/big.jpg",
          description:
              """Christopher George Latore Wallace (May 21, 1972 – March 9, 1997), better known by his stage names The Notorious B.I.G., Biggie Smalls, or simply Biggie,[2] was an American rapper. Rooted in East Coast hip hop and particularly gangsta rap, he is cited in various media lists as being one of the greatest rappers of all time. Wallace became known for his distinctive laid-back lyrical delivery, offsetting the lyrics' often grim content. His music was often semi-autobiographical, telling of hardship and criminality, but also of debauchery and celebration.[3]

Born and raised in Brooklyn, New York City, Wallace signed to Sean "Puffy" Combs' label Bad Boy Records as it launched in 1993, and gained exposure through features on several other artists' singles that year. His debut album Ready to Die (1994) was met with widespread critical acclaim, and included his signature songs "Juicy" and "Big Poppa". The album made him the central figure in East Coast hip hop, and restored New York's visibility at a time when the West Coast hip hop scene was dominating hip hop music.[4] Wallace was awarded the 1995 Billboard Music Awards' Rapper of the Year.[5] The following year, he led his protégé group Junior M.A.F.I.A., a team of himself and longtime friends, including Lil' Kim, to chart success.

During 1996, while recording his second album, Wallace became ensnarled in the escalating East Coast–West Coast hip hop feud. Following Tupac Shakur's death in a drive-by shooting in Las Vegas in September 1996, speculations of involvement in Shakur's murder by criminal elements orbiting the Bad Boy circle circulated as a result of Wallace's public feud with Shakur. On March 9, 1997, six months after Shakur's death, Wallace was murdered by an unidentified assailant in a drive-by shooting while visiting Los Angeles. Wallace's second album Life After Death, a double album, was released two weeks later. It reached number one on the Billboard 200, and eventually achieved a diamond certification in the United States.[6]

With two more posthumous albums released, Wallace has certified sales of over 28 million copies in the United States,[7] including 21 million albums.[8] Rolling Stone has called him the "greatest rapper that ever lived",[9] and Billboard named him the greatest rapper of all time.[10] The Source magazine named him the greatest rapper of all time in its 150th issue. In 2006, MTV ranked him at No. 3 on their list of The Greatest MCs of All Time, calling him possibly "the most skillful ever on the mic".[11] In 2020, he was inducted into the Rock and Roll Hall of Fame. """),
      ArtistsBio(
          name: "Kanye West",
          birthPlace: 'Atlanta, Georgia, U.S.',
          birthDay: "June 8, 1977",
          img: "images/KanyeWest.jpg",
          description:
              """Ye[a] (/jeɪ/ YAY; born Kanye Omari West /ˈkɑːnjeɪ/ KAHN-yay; June 8, 1977) is an American rapper, singer, songwriter, record producer, and fashion designer.[1][2][3][4]

Born in Atlanta and raised in Chicago,[5][6] West gained recognition as a producer for Roc-A-Fella Records in the early 2000s, producing singles for several artists and developing the "chipmunk soul" sampling style. Intent on pursuing a solo career as a rapper, he released his debut studio album, The College Dropout (2004), to critical and commercial success. He founded the record label GOOD Music later that year. West explored diverse musical elements like orchestras, synthesizers, and autotune on the albums Late Registration (2005), Graduation (2007), and 808s & Heartbreak (2008). His fifth and sixth albums My Beautiful Dark Twisted Fantasy (2010) and Yeezus (2013) were also met with critical and commercial success. West further diversified his musical styles on The Life of Pablo (2016) and Ye (2018) and explored Christian and gospel music on Jesus Is King (2019). His tenth album Donda (2021) was released to continued commercial success but mixed critical reception. West's discography also includes the two full-length collaborative albums Watch the Throne (2011) with Jay-Z and Kids See Ghosts (2018) with Kid Cudi.

One of the world's best-selling music artists, with over 160 million records sold, West has won 22 Grammy Awards and 75 nominations, the joint tenth-most of all time, and the joint-most Grammy awards of any rapper along with Jay-Z.[7] Among his other awards are the Billboard Artist Achievement Award, a joint-record three Brit Awards for Best International Male Solo Artist and the Michael Jackson Video Vanguard Award.[8] Six of West's albums were included on Rolling Stone's 2020 500 Greatest Albums of All Time list with the same publication naming him one of the 100 Greatest Songwriters of All Time.[9] He holds the joint record (with Bob Dylan) for most albums (4) topping the annual Pazz & Jop critic poll, and has the 5th most appearances on the Billboard Hot 100 (133 entries). Time named him one of the 100 most influential people in the world in 2005 and 2015.[10][11] As a fashion designer, he has collaborated with Nike, Louis Vuitton, Gap, and A.P.C. on clothing and footwear and led the Yeezy collaboration with Adidas. He is also the founder and head of the creative content company Donda.

West's outspoken views have received significant media coverage; he has been a frequent source of controversy due to his conduct on social media[12] and at awards shows and public settings, as well as his comments on the music and fashion industries, U.S. politics, race, and slavery. His Christian faith, high-profile marriage to Kim Kardashian, and mental health have also been topics of media attention.[13][14] In 2020, West launched an unsuccessful independent presidential campaign that primarily advocated for a consistent life ethic. In 2022, he was widely condemned and lost many sponsors and partnerships—including his collaborations with Adidas, Gap, and Balenciaga—after making a series of antisemitic statements.[15][16] In November 2022, he announced his 2024 presidential campaign, appearing publicly with Nick Fuentes, a white supremacist. He later publicly praised Adolf Hitler, denied the Holocaust, and identified as a Nazi."""),
      ArtistsBio(
          name: "Lil Wayne",
          birthPlace: 'New Orleans, Louisiana,\n U.S.',
          birthDay: "September 27, 1982",
          img: "images/Lil Wayne.jpg",
          description:
              """Dwayne Michael Carter Jr. (born September 27, 1982),[2] known professionally as Lil Wayne, is an American rapper, singer, songwriter, and record executive. His career began in 1995, at the age of 12, when he was signed by rapper Birdman, joining Cash Money Records as the youngest member of the label.[3] From then on, Wayne was the flagship artist of Cash Money Records before ending his association with the company in June 2018.[4] Regarded as one of the most influential hip hop artists of his generation by XXL,[5] he has often been cited as one of the greatest rappers of all time.[6][7]

In 1995, Wayne was put in a duo with label-mate B.G. (at the time known as Lil Doogie) and they recorded an album, True Story, released that year, although Wayne (at the time known as Baby D) only appeared on three tracks.[8] Wayne and B.G. soon joined the southern hip hop group Hot Boys, with Cash Money label-mates Juvenile and Turk in 1997; they released their debut album Get It How U Live! in October that year. The Hot Boys became popular following the release of the album Guerrilla Warfare (1999) and the song "Bling Bling".[citation needed]

Lil Wayne's solo debut album Tha Block Is Hot (1999) was his solo breakthrough, and he reached higher popularity with his fourth album Tha Carter (2004) and fifth album Tha Carter II (2005), as well as several mixtapes and collaborations throughout 2006 and 2007. He gained more prominence within the music industry with his sixth album Tha Carter III (2008), with first-week sales of over one million copies in the US. The album won the Grammy Award for Best Rap Album and included successful singles "A Milli", "Got Money" (featuring T-Pain), and "Lollipop" (featuring Static Major)—the latter being his first single to reach number one on the Billboard Hot 100.

In February 2010, Wayne released his seventh studio album, Rebirth, which experimented with rap rock and was met with generally negative reviews. A month later in March 2010, Lil Wayne began serving an 8-month jail sentence in New York after being convicted of criminal possession of a weapon stemming from an incident in July 2007. His eighth studio album I Am Not a Human Being (2010) was released during his incarceration, while his 2011 album Tha Carter IV was released following his release. Tha Carter IV sold 964,000 copies in its first week in the United States.[9] His twelfth studio album Tha Carter V was released in 2018 after multiple delays. Wayne's thirteenth album, Funeral, was released in early 2020.[10]

Lil Wayne has sold over 120 million records worldwide, including more than 20 million albums and 70 million digital tracks in the United States, making him one of the world's best-selling music artists.[11][12][13] He has won five Grammy Awards, 11 BET Awards, four Billboard Music Awards, two MTV Video Music Awards and eight NAACP Image Awards. On September 27, 2012, he became the first male artist to surpass Elvis Presley with the most entries on the Billboard Hot 100, with 109 songs.[14][15] Lil Wayne also currently serves as the chief executive officer (CEO) of his own label, Young Money Entertainment."""),
      ArtistsBio(
          name: "Drake",
          birthPlace: 'Toronto, Ontario, Canada',
          birthDay: "October 24, 1986",
          img: "images/Drake.jpg",
          description:
              """Aubrey Drake Graham[4] (/ɔːˈbriː/ aw-BREE; born October 24, 1986) is a Canadian rapper and singer.[5] An influential figure in contemporary popular music, Drake has been credited for popularizing singing and R&B sensibilities in hip hop. Gaining recognition by starring as Jimmy Brooks in the CTV teen drama series Degrassi: The Next Generation (2001–08), Drake pursued a career in music releasing his debut mixtape Room for Improvement in 2006. He followed this with the mixtapes Comeback Season (2007) and So Far Gone (2009) before signing with Young Money Entertainment.[6]

Drake's first three albums, Thank Me Later (2010), Take Care (2011) and Nothing Was the Same (2013), were all critical successes and propelled him to the forefront of hip hop.[7] His fourth album, Views (2016), saw exploration of dancehall and stood atop the Billboard 200 for 13 non-consecutive weeks, making it the first album by a male artist to do so in over a decade, and featured the chart record-setting lead single "One Dance".[8] In 2018, Drake released the double album Scorpion, which contained the Billboard Hot 100 number-one singles "God's Plan", "Nice for What", and "In My Feelings".[9] Drake's widely anticipated sixth album, Certified Lover Boy (2021), achieved nine top 10 hits on the Hot 100, setting the then-record for most US top-ten hits from one album, with its lead single "Way 2 Sexy" reaching number one.[10] In 2022, Drake released the house-inspired album Honestly, Nevermind and the collaborative album, Her Loss, with 21 Savage. Known for frequent accompanying releases to his albums, Drake achieved critical and commercial success with the mixtapes If You're Reading This It's Too Late (2015) and More Life (2017).

As an entrepreneur, Drake founded the OVO Sound record label with longtime collaborator 40 in 2012. In 2013, Drake became the "global ambassador" of the Toronto Raptors, joining their executive committee and later obtaining naming rights to their practice facility. In 2016, he began collaborating with Brent Hocking on the bourbon whiskey Virginia Black.[11] Drake heads the OVO fashion label and the Nocta collaboration with Nike, and founded the production company DreamCrew and the fragrance house Better World. In 2018, Drake was reportedly responsible for 5 percent (CAD\$440 million) of Toronto's CAD\$8.8 billion annual tourism income.[12] In 2022, he became a part owner of Italian football club A.C. Milan.

Among the world's best-selling music artists, with over 170 million records sold, Drake is ranked as the highest-certified digital singles artist in the United States by the RIAA.[13] He has won four Grammy Awards, six American Music Awards, a record 34 Billboard Music Awards, two Brit Awards, and three Juno Awards. Drake has achieved 11 number-one hits on the Billboard Hot 100 and holds further Hot 100 records;[14] he has the most top 10 singles (67), most charted songs (293),[15] the most simultaneously charted songs in one week (27), the most Hot 100 debuts in one week (22), and the most continuous time on the Hot 100 (431 weeks). He additionally has the most number-one singles on the R&B/Hip-Hop Airplay, Hot R&B/Hip-Hop Songs, Hot Rap Songs, and Rhythmic Airplay charts."""),
      ArtistsBio(
        name: "Jay-Z",
        birthPlace: 'New York City, U.S.',
        birthDay: "December 4, 1969",
        img: "images/jayz.jpg",
        description:
            """Shawn Corey Carter (born December 4, 1969), known professionally as Jay-Z,[a] is an American rapper, record producer, entrepreneur, and founder of Manhattan-based conglomerate talent and entertainment agency Roc Nation. He is regarded as one of the greatest rappers of all time.[8] He was the CEO of Def Jam Recordings and he has been central to the creative and commercial success of artists including Kanye West, Rihanna, and J. Cole.[9][10]

Born and raised in New York City, Jay-Z first began his musical career in the late 1980s; he co-founded the record label Roc-A-Fella Records in 1995 and released his debut studio album Reasonable Doubt in 1996. The album was released to widespread critical success, and solidified his standing in the music industry. He went on to release twelve additional albums, including the acclaimed albums The Blueprint (2001), The Black Album (2003), American Gangster (2007), and 4:44 (2017).[11][12] He also released the full-length collaborative albums Watch the Throne (2011) with Kanye West and Everything Is Love (2018) with his wife Beyoncé, respectively.[13]

Through his business ventures Jay-Z has become the first hip-hop billionaire.[14][15] In 1999, he founded the clothing retailer Rocawear,[16] and in 2003, he founded the luxury sports bar chain 40/40 Club. Both businesses have grown to become multi-million-dollar corporations, and allowed him to start up Roc Nation in 2008. In 2015, he acquired the tech company Aspiro and took charge of their media streaming service Tidal.[17][18] In 2020, he launched "Monogram", a line of cannabis products.[19]

One of the world's best-selling music artists, with over 140 million records sold, Jay-Z has won 24 Grammy Awards, the joint-most Grammy awards of any rapper along with Kanye West. Jay-Z also holds the record for the most number-one albums by a solo artist on the Billboard 200 (14).[20][21] Additionally, he is a recipient of the NAACP's President's Award, a Primetime Emmy Award, and a Sports Emmy Award; and has also received a nomination for a Tony Award. Ranked by Billboard and Rolling Stone as one of the 100 Greatest Artists of All Time,[22][23] Jay-Z was the first rapper honored in the Songwriters Hall of Fame,[24] and the first solo living rapper inducted in the Rock and Roll Hall of Fame.[25] In 2013, Time named him one of the 100 most influential people in the world.[26]""",
      ),
      ArtistsBio(
          name: "Eminem",
          birthPlace: 'St. Joseph, Missouri, U.S.',
          birthDay: "October 17, 1972",
          img: "images/em.jpg",
          description:
              """Marshall Bruce Mathers III (born October 17, 1972), known professionally as Eminem (/ˌɛmɪˈnɛm/; often stylized as EMINƎM), is an American rapper. He is credited with popularizing hip hop in middle America and is critically acclaimed as one of the greatest rappers of all time.[2] Eminem's global success and acclaimed works are widely regarded as having broken racial barriers for the acceptance of white rappers in popular music. While much of his transgressive work during the late 1990s and early 2000s made him widely controversial, he came to be a representation of popular angst of the American underclass and has been cited as an influence for many artists of various genres.

After the release of his debut album Infinite (1996) and the extended play Slim Shady EP (1997), Eminem signed with Dr. Dre's Aftermath Entertainment and subsequently achieved mainstream popularity in 1999 with The Slim Shady LP. His next two releases, The Marshall Mathers LP (2000) and The Eminem Show (2002), were worldwide successes and were both nominated for the Grammy Award for Album of the Year. After the release of his next album, Encore (2004), Eminem went on hiatus in 2005, largely due to a prescription drug addiction.[3] He returned to the music industry four years later with the release of Relapse (2009) and Recovery was released the following year. Recovery was the best-selling album worldwide of 2010, making it Eminem's second album, after The Eminem Show in 2002, to be the best-selling album of the year worldwide. In the following years, he released the US number one albums The Marshall Mathers LP 2 (2013), Revival (2017), Kamikaze (2018) and Music to Be Murdered By (2020).

Eminem made his debut in the film industry with the musical drama film 8 Mile (2002), playing a fictionalized version of himself, and his track "Lose Yourself" from its soundtrack won the Academy Award for Best Original Song, making him the first hip hop artist ever to win the award.[4] Eminem has made cameo appearances in the films The Wash (2001), Funny People (2009) and The Interview (2014) and the television series Entourage (2010). He has also developed other ventures, including Shady Records, a joint venture with manager Paul Rosenberg, which helped launch the careers of artists such as 50 Cent, D12 and Obie Trice, among others. He has also established his own channel, Shade 45, on Sirius XM Radio.

In addition to his solo career, Eminem was a member of the hip hop group D12. He is also known for collaborations with fellow Detroit-based rapper Royce da 5'9"; the two are collectively known as Bad Meets Evil.

Eminem is among the best-selling music artists of all time, with estimated worldwide sales of over 220 million records. He was the best-selling music artist in the United States of the 2000s and the best-selling male music artist in the United States of the 2010s, third overall. Billboard named him the "Artist of the Decade (2000–2009)". He has had ten number-one albums on the Billboard 200—which all consecutively debuted at number one on the chart, making him the first artist to achieve this[5]—and five number-one singles on the Billboard Hot 100.[6] The Marshall Mathers LP, The Eminem Show, Curtain Call: The Hits (2005), "Lose Yourself", "Love the Way You Lie" and "Not Afraid" have all been certified Diamond or higher by the Recording Industry Association of America (RIAA).[7] Rolling Stone has included him in its lists of the 100 Greatest Artists of All Time and the 100 Greatest Songwriters of All Time. He has won numerous awards, including 15 Grammy Awards, eight American Music Awards, 17 Billboard Music Awards, an Academy Award, a Primetime Emmy Award and an MTV Europe Music Global Icon Award. In November 2022, Eminem was inducted into the Rock and Roll Hall of Fame.[8]"""),
      ArtistsBio(
          name: "Notorious B.I.G.",
          birthPlace: 'New York City, U.S.',
          birthDay: "May 21, 1972",
          img: "images/big.jpg",
          description:
              """Christopher George Latore Wallace (May 21, 1972 – March 9, 1997), better known by his stage names The Notorious B.I.G., Biggie Smalls, or simply Biggie,[2] was an American rapper. Rooted in East Coast hip hop and particularly gangsta rap, he is cited in various media lists as being one of the greatest rappers of all time. Wallace became known for his distinctive laid-back lyrical delivery, offsetting the lyrics' often grim content. His music was often semi-autobiographical, telling of hardship and criminality, but also of debauchery and celebration.[3]

Born and raised in Brooklyn, New York City, Wallace signed to Sean "Puffy" Combs' label Bad Boy Records as it launched in 1993, and gained exposure through features on several other artists' singles that year. His debut album Ready to Die (1994) was met with widespread critical acclaim, and included his signature songs "Juicy" and "Big Poppa". The album made him the central figure in East Coast hip hop, and restored New York's visibility at a time when the West Coast hip hop scene was dominating hip hop music.[4] Wallace was awarded the 1995 Billboard Music Awards' Rapper of the Year.[5] The following year, he led his protégé group Junior M.A.F.I.A., a team of himself and longtime friends, including Lil' Kim, to chart success.

During 1996, while recording his second album, Wallace became ensnarled in the escalating East Coast–West Coast hip hop feud. Following Tupac Shakur's death in a drive-by shooting in Las Vegas in September 1996, speculations of involvement in Shakur's murder by criminal elements orbiting the Bad Boy circle circulated as a result of Wallace's public feud with Shakur. On March 9, 1997, six months after Shakur's death, Wallace was murdered by an unidentified assailant in a drive-by shooting while visiting Los Angeles. Wallace's second album Life After Death, a double album, was released two weeks later. It reached number one on the Billboard 200, and eventually achieved a diamond certification in the United States.[6]

With two more posthumous albums released, Wallace has certified sales of over 28 million copies in the United States,[7] including 21 million albums.[8] Rolling Stone has called him the "greatest rapper that ever lived",[9] and Billboard named him the greatest rapper of all time.[10] The Source magazine named him the greatest rapper of all time in its 150th issue. In 2006, MTV ranked him at No. 3 on their list of The Greatest MCs of All Time, calling him possibly "the most skillful ever on the mic".[11] In 2020, he was inducted into the Rock and Roll Hall of Fame. """),
      ArtistsBio(
          name: "Kanye West",
          birthPlace: 'Atlanta, Georgia, U.S.',
          birthDay: "June 8, 1977",
          img: "images/KanyeWest.jpg",
          description:
              """Ye[a] (/jeɪ/ YAY; born Kanye Omari West /ˈkɑːnjeɪ/ KAHN-yay; June 8, 1977) is an American rapper, singer, songwriter, record producer, and fashion designer.[1][2][3][4]

Born in Atlanta and raised in Chicago,[5][6] West gained recognition as a producer for Roc-A-Fella Records in the early 2000s, producing singles for several artists and developing the "chipmunk soul" sampling style. Intent on pursuing a solo career as a rapper, he released his debut studio album, The College Dropout (2004), to critical and commercial success. He founded the record label GOOD Music later that year. West explored diverse musical elements like orchestras, synthesizers, and autotune on the albums Late Registration (2005), Graduation (2007), and 808s & Heartbreak (2008). His fifth and sixth albums My Beautiful Dark Twisted Fantasy (2010) and Yeezus (2013) were also met with critical and commercial success. West further diversified his musical styles on The Life of Pablo (2016) and Ye (2018) and explored Christian and gospel music on Jesus Is King (2019). His tenth album Donda (2021) was released to continued commercial success but mixed critical reception. West's discography also includes the two full-length collaborative albums Watch the Throne (2011) with Jay-Z and Kids See Ghosts (2018) with Kid Cudi.

One of the world's best-selling music artists, with over 160 million records sold, West has won 22 Grammy Awards and 75 nominations, the joint tenth-most of all time, and the joint-most Grammy awards of any rapper along with Jay-Z.[7] Among his other awards are the Billboard Artist Achievement Award, a joint-record three Brit Awards for Best International Male Solo Artist and the Michael Jackson Video Vanguard Award.[8] Six of West's albums were included on Rolling Stone's 2020 500 Greatest Albums of All Time list with the same publication naming him one of the 100 Greatest Songwriters of All Time.[9] He holds the joint record (with Bob Dylan) for most albums (4) topping the annual Pazz & Jop critic poll, and has the 5th most appearances on the Billboard Hot 100 (133 entries). Time named him one of the 100 most influential people in the world in 2005 and 2015.[10][11] As a fashion designer, he has collaborated with Nike, Louis Vuitton, Gap, and A.P.C. on clothing and footwear and led the Yeezy collaboration with Adidas. He is also the founder and head of the creative content company Donda.

West's outspoken views have received significant media coverage; he has been a frequent source of controversy due to his conduct on social media[12] and at awards shows and public settings, as well as his comments on the music and fashion industries, U.S. politics, race, and slavery. His Christian faith, high-profile marriage to Kim Kardashian, and mental health have also been topics of media attention.[13][14] In 2020, West launched an unsuccessful independent presidential campaign that primarily advocated for a consistent life ethic. In 2022, he was widely condemned and lost many sponsors and partnerships—including his collaborations with Adidas, Gap, and Balenciaga—after making a series of antisemitic statements.[15][16] In November 2022, he announced his 2024 presidential campaign, appearing publicly with Nick Fuentes, a white supremacist. He later publicly praised Adolf Hitler, denied the Holocaust, and identified as a Nazi."""),
      ArtistsBio(
          name: "Lil Wayne",
          birthPlace: 'New Orleans, Louisiana, U.S.',
          birthDay: "September 27, 1982",
          img: "images/Lil Wayne.jpg",
          description:
              """Dwayne Michael Carter Jr. (born September 27, 1982),[2] known professionally as Lil Wayne, is an American rapper, singer, songwriter, and record executive. His career began in 1995, at the age of 12, when he was signed by rapper Birdman, joining Cash Money Records as the youngest member of the label.[3] From then on, Wayne was the flagship artist of Cash Money Records before ending his association with the company in June 2018.[4] Regarded as one of the most influential hip hop artists of his generation by XXL,[5] he has often been cited as one of the greatest rappers of all time.[6][7]

In 1995, Wayne was put in a duo with label-mate B.G. (at the time known as Lil Doogie) and they recorded an album, True Story, released that year, although Wayne (at the time known as Baby D) only appeared on three tracks.[8] Wayne and B.G. soon joined the southern hip hop group Hot Boys, with Cash Money label-mates Juvenile and Turk in 1997; they released their debut album Get It How U Live! in October that year. The Hot Boys became popular following the release of the album Guerrilla Warfare (1999) and the song "Bling Bling".[citation needed]

Lil Wayne's solo debut album Tha Block Is Hot (1999) was his solo breakthrough, and he reached higher popularity with his fourth album Tha Carter (2004) and fifth album Tha Carter II (2005), as well as several mixtapes and collaborations throughout 2006 and 2007. He gained more prominence within the music industry with his sixth album Tha Carter III (2008), with first-week sales of over one million copies in the US. The album won the Grammy Award for Best Rap Album and included successful singles "A Milli", "Got Money" (featuring T-Pain), and "Lollipop" (featuring Static Major)—the latter being his first single to reach number one on the Billboard Hot 100.

In February 2010, Wayne released his seventh studio album, Rebirth, which experimented with rap rock and was met with generally negative reviews. A month later in March 2010, Lil Wayne began serving an 8-month jail sentence in New York after being convicted of criminal possession of a weapon stemming from an incident in July 2007. His eighth studio album I Am Not a Human Being (2010) was released during his incarceration, while his 2011 album Tha Carter IV was released following his release. Tha Carter IV sold 964,000 copies in its first week in the United States.[9] His twelfth studio album Tha Carter V was released in 2018 after multiple delays. Wayne's thirteenth album, Funeral, was released in early 2020.[10]

Lil Wayne has sold over 120 million records worldwide, including more than 20 million albums and 70 million digital tracks in the United States, making him one of the world's best-selling music artists.[11][12][13] He has won five Grammy Awards, 11 BET Awards, four Billboard Music Awards, two MTV Video Music Awards and eight NAACP Image Awards. On September 27, 2012, he became the first male artist to surpass Elvis Presley with the most entries on the Billboard Hot 100, with 109 songs.[14][15] Lil Wayne also currently serves as the chief executive officer (CEO) of his own label, Young Money Entertainment."""),
      ArtistsBio(
          name: "Drake",
          birthPlace: 'Toronto, Ontario, Canada',
          birthDay: "October 24, 1986",
          img: "images/Drake.jpg",
          description:
              """Aubrey Drake Graham[4] (/ɔːˈbriː/ aw-BREE; born October 24, 1986) is a Canadian rapper and singer.[5] An influential figure in contemporary popular music, Drake has been credited for popularizing singing and R&B sensibilities in hip hop. Gaining recognition by starring as Jimmy Brooks in the CTV teen drama series Degrassi: The Next Generation (2001–08), Drake pursued a career in music releasing his debut mixtape Room for Improvement in 2006. He followed this with the mixtapes Comeback Season (2007) and So Far Gone (2009) before signing with Young Money Entertainment.[6]

Drake's first three albums, Thank Me Later (2010), Take Care (2011) and Nothing Was the Same (2013), were all critical successes and propelled him to the forefront of hip hop.[7] His fourth album, Views (2016), saw exploration of dancehall and stood atop the Billboard 200 for 13 non-consecutive weeks, making it the first album by a male artist to do so in over a decade, and featured the chart record-setting lead single "One Dance".[8] In 2018, Drake released the double album Scorpion, which contained the Billboard Hot 100 number-one singles "God's Plan", "Nice for What", and "In My Feelings".[9] Drake's widely anticipated sixth album, Certified Lover Boy (2021), achieved nine top 10 hits on the Hot 100, setting the then-record for most US top-ten hits from one album, with its lead single "Way 2 Sexy" reaching number one.[10] In 2022, Drake released the house-inspired album Honestly, Nevermind and the collaborative album, Her Loss, with 21 Savage. Known for frequent accompanying releases to his albums, Drake achieved critical and commercial success with the mixtapes If You're Reading This It's Too Late (2015) and More Life (2017).

As an entrepreneur, Drake founded the OVO Sound record label with longtime collaborator 40 in 2012. In 2013, Drake became the "global ambassador" of the Toronto Raptors, joining their executive committee and later obtaining naming rights to their practice facility. In 2016, he began collaborating with Brent Hocking on the bourbon whiskey Virginia Black.[11] Drake heads the OVO fashion label and the Nocta collaboration with Nike, and founded the production company DreamCrew and the fragrance house Better World. In 2018, Drake was reportedly responsible for 5 percent (CAD\$440 million) of Toronto's CAD\$8.8 billion annual tourism income.[12] In 2022, he became a part owner of Italian football club A.C. Milan.

Among the world's best-selling music artists, with over 170 million records sold, Drake is ranked as the highest-certified digital singles artist in the United States by the RIAA.[13] He has won four Grammy Awards, six American Music Awards, a record 34 Billboard Music Awards, two Brit Awards, and three Juno Awards. Drake has achieved 11 number-one hits on the Billboard Hot 100 and holds further Hot 100 records;[14] he has the most top 10 singles (67), most charted songs (293),[15] the most simultaneously charted songs in one week (27), the most Hot 100 debuts in one week (22), and the most continuous time on the Hot 100 (431 weeks). He additionally has the most number-one singles on the R&B/Hip-Hop Airplay, Hot R&B/Hip-Hop Songs, Hot Rap Songs, and Rhythmic Airplay charts."""),
      ArtistsBio(
        name: "Jay-Z",
        birthPlace: 'New York City, U.S.',
        birthDay: "December 4, 1969",
        img: "images/jayz.jpg",
        description:
            """Shawn Corey Carter (born December 4, 1969), known professionally as Jay-Z,[a] is an American rapper, record producer, entrepreneur, and founder of Manhattan-based conglomerate talent and entertainment agency Roc Nation. He is regarded as one of the greatest rappers of all time.[8] He was the CEO of Def Jam Recordings and he has been central to the creative and commercial success of artists including Kanye West, Rihanna, and J. Cole.[9][10]

Born and raised in New York City, Jay-Z first began his musical career in the late 1980s; he co-founded the record label Roc-A-Fella Records in 1995 and released his debut studio album Reasonable Doubt in 1996. The album was released to widespread critical success, and solidified his standing in the music industry. He went on to release twelve additional albums, including the acclaimed albums The Blueprint (2001), The Black Album (2003), American Gangster (2007), and 4:44 (2017).[11][12] He also released the full-length collaborative albums Watch the Throne (2011) with Kanye West and Everything Is Love (2018) with his wife Beyoncé, respectively.[13]

Through his business ventures Jay-Z has become the first hip-hop billionaire.[14][15] In 1999, he founded the clothing retailer Rocawear,[16] and in 2003, he founded the luxury sports bar chain 40/40 Club. Both businesses have grown to become multi-million-dollar corporations, and allowed him to start up Roc Nation in 2008. In 2015, he acquired the tech company Aspiro and took charge of their media streaming service Tidal.[17][18] In 2020, he launched "Monogram", a line of cannabis products.[19]

One of the world's best-selling music artists, with over 140 million records sold, Jay-Z has won 24 Grammy Awards, the joint-most Grammy awards of any rapper along with Kanye West. Jay-Z also holds the record for the most number-one albums by a solo artist on the Billboard 200 (14).[20][21] Additionally, he is a recipient of the NAACP's President's Award, a Primetime Emmy Award, and a Sports Emmy Award; and has also received a nomination for a Tony Award. Ranked by Billboard and Rolling Stone as one of the 100 Greatest Artists of All Time,[22][23] Jay-Z was the first rapper honored in the Songwriters Hall of Fame,[24] and the first solo living rapper inducted in the Rock and Roll Hall of Fame.[25] In 2013, Time named him one of the 100 most influential people in the world.[26]""",
      ),
      ArtistsBio(
          name: "Eminem",
          birthPlace: 'St. Joseph, Missouri, U.S.',
          birthDay: "October 17, 1972",
          img: "images/em.jpg",
          description:
              """Marshall Bruce Mathers III (born October 17, 1972), known professionally as Eminem (/ˌɛmɪˈnɛm/; often stylized as EMINƎM), is an American rapper. He is credited with popularizing hip hop in middle America and is critically acclaimed as one of the greatest rappers of all time.[2] Eminem's global success and acclaimed works are widely regarded as having broken racial barriers for the acceptance of white rappers in popular music. While much of his transgressive work during the late 1990s and early 2000s made him widely controversial, he came to be a representation of popular angst of the American underclass and has been cited as an influence for many artists of various genres.

After the release of his debut album Infinite (1996) and the extended play Slim Shady EP (1997), Eminem signed with Dr. Dre's Aftermath Entertainment and subsequently achieved mainstream popularity in 1999 with The Slim Shady LP. His next two releases, The Marshall Mathers LP (2000) and The Eminem Show (2002), were worldwide successes and were both nominated for the Grammy Award for Album of the Year. After the release of his next album, Encore (2004), Eminem went on hiatus in 2005, largely due to a prescription drug addiction.[3] He returned to the music industry four years later with the release of Relapse (2009) and Recovery was released the following year. Recovery was the best-selling album worldwide of 2010, making it Eminem's second album, after The Eminem Show in 2002, to be the best-selling album of the year worldwide. In the following years, he released the US number one albums The Marshall Mathers LP 2 (2013), Revival (2017), Kamikaze (2018) and Music to Be Murdered By (2020).

Eminem made his debut in the film industry with the musical drama film 8 Mile (2002), playing a fictionalized version of himself, and his track "Lose Yourself" from its soundtrack won the Academy Award for Best Original Song, making him the first hip hop artist ever to win the award.[4] Eminem has made cameo appearances in the films The Wash (2001), Funny People (2009) and The Interview (2014) and the television series Entourage (2010). He has also developed other ventures, including Shady Records, a joint venture with manager Paul Rosenberg, which helped launch the careers of artists such as 50 Cent, D12 and Obie Trice, among others. He has also established his own channel, Shade 45, on Sirius XM Radio.

In addition to his solo career, Eminem was a member of the hip hop group D12. He is also known for collaborations with fellow Detroit-based rapper Royce da 5'9"; the two are collectively known as Bad Meets Evil.

Eminem is among the best-selling music artists of all time, with estimated worldwide sales of over 220 million records. He was the best-selling music artist in the United States of the 2000s and the best-selling male music artist in the United States of the 2010s, third overall. Billboard named him the "Artist of the Decade (2000–2009)". He has had ten number-one albums on the Billboard 200—which all consecutively debuted at number one on the chart, making him the first artist to achieve this[5]—and five number-one singles on the Billboard Hot 100.[6] The Marshall Mathers LP, The Eminem Show, Curtain Call: The Hits (2005), "Lose Yourself", "Love the Way You Lie" and "Not Afraid" have all been certified Diamond or higher by the Recording Industry Association of America (RIAA).[7] Rolling Stone has included him in its lists of the 100 Greatest Artists of All Time and the 100 Greatest Songwriters of All Time. He has won numerous awards, including 15 Grammy Awards, eight American Music Awards, 17 Billboard Music Awards, an Academy Award, a Primetime Emmy Award and an MTV Europe Music Global Icon Award. In November 2022, Eminem was inducted into the Rock and Roll Hall of Fame.[8]"""),
      ArtistsBio(
          name: "Notorious B.I.G.",
          birthPlace: 'New York City, U.S.',
          birthDay: "May 21, 1972",
          img: "images/big.jpg",
          description:
              """Christopher George Latore Wallace (May 21, 1972 – March 9, 1997), better known by his stage names The Notorious B.I.G., Biggie Smalls, or simply Biggie,[2] was an American rapper. Rooted in East Coast hip hop and particularly gangsta rap, he is cited in various media lists as being one of the greatest rappers of all time. Wallace became known for his distinctive laid-back lyrical delivery, offsetting the lyrics' often grim content. His music was often semi-autobiographical, telling of hardship and criminality, but also of debauchery and celebration.[3]

Born and raised in Brooklyn, New York City, Wallace signed to Sean "Puffy" Combs' label Bad Boy Records as it launched in 1993, and gained exposure through features on several other artists' singles that year. His debut album Ready to Die (1994) was met with widespread critical acclaim, and included his signature songs "Juicy" and "Big Poppa". The album made him the central figure in East Coast hip hop, and restored New York's visibility at a time when the West Coast hip hop scene was dominating hip hop music.[4] Wallace was awarded the 1995 Billboard Music Awards' Rapper of the Year.[5] The following year, he led his protégé group Junior M.A.F.I.A., a team of himself and longtime friends, including Lil' Kim, to chart success.

During 1996, while recording his second album, Wallace became ensnarled in the escalating East Coast–West Coast hip hop feud. Following Tupac Shakur's death in a drive-by shooting in Las Vegas in September 1996, speculations of involvement in Shakur's murder by criminal elements orbiting the Bad Boy circle circulated as a result of Wallace's public feud with Shakur. On March 9, 1997, six months after Shakur's death, Wallace was murdered by an unidentified assailant in a drive-by shooting while visiting Los Angeles. Wallace's second album Life After Death, a double album, was released two weeks later. It reached number one on the Billboard 200, and eventually achieved a diamond certification in the United States.[6]

With two more posthumous albums released, Wallace has certified sales of over 28 million copies in the United States,[7] including 21 million albums.[8] Rolling Stone has called him the "greatest rapper that ever lived",[9] and Billboard named him the greatest rapper of all time.[10] The Source magazine named him the greatest rapper of all time in its 150th issue. In 2006, MTV ranked him at No. 3 on their list of The Greatest MCs of All Time, calling him possibly "the most skillful ever on the mic".[11] In 2020, he was inducted into the Rock and Roll Hall of Fame. """),
      ArtistsBio(
          name: "Kanye West",
          birthPlace: 'Atlanta, Georgia, U.S.',
          birthDay: "June 8, 1977",
          img: "images/KanyeWest.jpg",
          description:
              """Ye[a] (/jeɪ/ YAY; born Kanye Omari West /ˈkɑːnjeɪ/ KAHN-yay; June 8, 1977) is an American rapper, singer, songwriter, record producer, and fashion designer.[1][2][3][4]

Born in Atlanta and raised in Chicago,[5][6] West gained recognition as a producer for Roc-A-Fella Records in the early 2000s, producing singles for several artists and developing the "chipmunk soul" sampling style. Intent on pursuing a solo career as a rapper, he released his debut studio album, The College Dropout (2004), to critical and commercial success. He founded the record label GOOD Music later that year. West explored diverse musical elements like orchestras, synthesizers, and autotune on the albums Late Registration (2005), Graduation (2007), and 808s & Heartbreak (2008). His fifth and sixth albums My Beautiful Dark Twisted Fantasy (2010) and Yeezus (2013) were also met with critical and commercial success. West further diversified his musical styles on The Life of Pablo (2016) and Ye (2018) and explored Christian and gospel music on Jesus Is King (2019). His tenth album Donda (2021) was released to continued commercial success but mixed critical reception. West's discography also includes the two full-length collaborative albums Watch the Throne (2011) with Jay-Z and Kids See Ghosts (2018) with Kid Cudi.

One of the world's best-selling music artists, with over 160 million records sold, West has won 22 Grammy Awards and 75 nominations, the joint tenth-most of all time, and the joint-most Grammy awards of any rapper along with Jay-Z.[7] Among his other awards are the Billboard Artist Achievement Award, a joint-record three Brit Awards for Best International Male Solo Artist and the Michael Jackson Video Vanguard Award.[8] Six of West's albums were included on Rolling Stone's 2020 500 Greatest Albums of All Time list with the same publication naming him one of the 100 Greatest Songwriters of All Time.[9] He holds the joint record (with Bob Dylan) for most albums (4) topping the annual Pazz & Jop critic poll, and has the 5th most appearances on the Billboard Hot 100 (133 entries). Time named him one of the 100 most influential people in the world in 2005 and 2015.[10][11] As a fashion designer, he has collaborated with Nike, Louis Vuitton, Gap, and A.P.C. on clothing and footwear and led the Yeezy collaboration with Adidas. He is also the founder and head of the creative content company Donda.

West's outspoken views have received significant media coverage; he has been a frequent source of controversy due to his conduct on social media[12] and at awards shows and public settings, as well as his comments on the music and fashion industries, U.S. politics, race, and slavery. His Christian faith, high-profile marriage to Kim Kardashian, and mental health have also been topics of media attention.[13][14] In 2020, West launched an unsuccessful independent presidential campaign that primarily advocated for a consistent life ethic. In 2022, he was widely condemned and lost many sponsors and partnerships—including his collaborations with Adidas, Gap, and Balenciaga—after making a series of antisemitic statements.[15][16] In November 2022, he announced his 2024 presidential campaign, appearing publicly with Nick Fuentes, a white supremacist. He later publicly praised Adolf Hitler, denied the Holocaust, and identified as a Nazi."""),
      ArtistsBio(
          name: "Lil Wayne",
          birthPlace: 'New Orleans, Louisiana, U.S.',
          birthDay: "September 27, 1982",
          img: "images/Lil Wayne.jpg",
          description:
              """Dwayne Michael Carter Jr. (born September 27, 1982),[2] known professionally as Lil Wayne, is an American rapper, singer, songwriter, and record executive. His career began in 1995, at the age of 12, when he was signed by rapper Birdman, joining Cash Money Records as the youngest member of the label.[3] From then on, Wayne was the flagship artist of Cash Money Records before ending his association with the company in June 2018.[4] Regarded as one of the most influential hip hop artists of his generation by XXL,[5] he has often been cited as one of the greatest rappers of all time.[6][7]

In 1995, Wayne was put in a duo with label-mate B.G. (at the time known as Lil Doogie) and they recorded an album, True Story, released that year, although Wayne (at the time known as Baby D) only appeared on three tracks.[8] Wayne and B.G. soon joined the southern hip hop group Hot Boys, with Cash Money label-mates Juvenile and Turk in 1997; they released their debut album Get It How U Live! in October that year. The Hot Boys became popular following the release of the album Guerrilla Warfare (1999) and the song "Bling Bling".[citation needed]

Lil Wayne's solo debut album Tha Block Is Hot (1999) was his solo breakthrough, and he reached higher popularity with his fourth album Tha Carter (2004) and fifth album Tha Carter II (2005), as well as several mixtapes and collaborations throughout 2006 and 2007. He gained more prominence within the music industry with his sixth album Tha Carter III (2008), with first-week sales of over one million copies in the US. The album won the Grammy Award for Best Rap Album and included successful singles "A Milli", "Got Money" (featuring T-Pain), and "Lollipop" (featuring Static Major)—the latter being his first single to reach number one on the Billboard Hot 100.

In February 2010, Wayne released his seventh studio album, Rebirth, which experimented with rap rock and was met with generally negative reviews. A month later in March 2010, Lil Wayne began serving an 8-month jail sentence in New York after being convicted of criminal possession of a weapon stemming from an incident in July 2007. His eighth studio album I Am Not a Human Being (2010) was released during his incarceration, while his 2011 album Tha Carter IV was released following his release. Tha Carter IV sold 964,000 copies in its first week in the United States.[9] His twelfth studio album Tha Carter V was released in 2018 after multiple delays. Wayne's thirteenth album, Funeral, was released in early 2020.[10]

Lil Wayne has sold over 120 million records worldwide, including more than 20 million albums and 70 million digital tracks in the United States, making him one of the world's best-selling music artists.[11][12][13] He has won five Grammy Awards, 11 BET Awards, four Billboard Music Awards, two MTV Video Music Awards and eight NAACP Image Awards. On September 27, 2012, he became the first male artist to surpass Elvis Presley with the most entries on the Billboard Hot 100, with 109 songs.[14][15] Lil Wayne also currently serves as the chief executive officer (CEO) of his own label, Young Money Entertainment."""),
      ArtistsBio(
          name: "Drake",
          birthPlace: 'Toronto, Ontario, Canada',
          birthDay: "October 24, 1986",
          img: "images/Drake.jpg",
          description:
              """Aubrey Drake Graham[4] (/ɔːˈbriː/ aw-BREE; born October 24, 1986) is a Canadian rapper and singer.[5] An influential figure in contemporary popular music, Drake has been credited for popularizing singing and R&B sensibilities in hip hop. Gaining recognition by starring as Jimmy Brooks in the CTV teen drama series Degrassi: The Next Generation (2001–08), Drake pursued a career in music releasing his debut mixtape Room for Improvement in 2006. He followed this with the mixtapes Comeback Season (2007) and So Far Gone (2009) before signing with Young Money Entertainment.[6]

Drake's first three albums, Thank Me Later (2010), Take Care (2011) and Nothing Was the Same (2013), were all critical successes and propelled him to the forefront of hip hop.[7] His fourth album, Views (2016), saw exploration of dancehall and stood atop the Billboard 200 for 13 non-consecutive weeks, making it the first album by a male artist to do so in over a decade, and featured the chart record-setting lead single "One Dance".[8] In 2018, Drake released the double album Scorpion, which contained the Billboard Hot 100 number-one singles "God's Plan", "Nice for What", and "In My Feelings".[9] Drake's widely anticipated sixth album, Certified Lover Boy (2021), achieved nine top 10 hits on the Hot 100, setting the then-record for most US top-ten hits from one album, with its lead single "Way 2 Sexy" reaching number one.[10] In 2022, Drake released the house-inspired album Honestly, Nevermind and the collaborative album, Her Loss, with 21 Savage. Known for frequent accompanying releases to his albums, Drake achieved critical and commercial success with the mixtapes If You're Reading This It's Too Late (2015) and More Life (2017).

As an entrepreneur, Drake founded the OVO Sound record label with longtime collaborator 40 in 2012. In 2013, Drake became the "global ambassador" of the Toronto Raptors, joining their executive committee and later obtaining naming rights to their practice facility. In 2016, he began collaborating with Brent Hocking on the bourbon whiskey Virginia Black.[11] Drake heads the OVO fashion label and the Nocta collaboration with Nike, and founded the production company DreamCrew and the fragrance house Better World. In 2018, Drake was reportedly responsible for 5 percent (CAD\$440 million) of Toronto's CAD\$8.8 billion annual tourism income.[12] In 2022, he became a part owner of Italian football club A.C. Milan.

Among the world's best-selling music artists, with over 170 million records sold, Drake is ranked as the highest-certified digital singles artist in the United States by the RIAA.[13] He has won four Grammy Awards, six American Music Awards, a record 34 Billboard Music Awards, two Brit Awards, and three Juno Awards. Drake has achieved 11 number-one hits on the Billboard Hot 100 and holds further Hot 100 records;[14] he has the most top 10 singles (67), most charted songs (293),[15] the most simultaneously charted songs in one week (27), the most Hot 100 debuts in one week (22), and the most continuous time on the Hot 100 (431 weeks). He additionally has the most number-one singles on the R&B/Hip-Hop Airplay, Hot R&B/Hip-Hop Songs, Hot Rap Songs, and Rhythmic Airplay charts."""),
    ];
  }
}
